with-expecter: true
dir: "internal/mocks/{{.InterfaceDirRelative}}"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
packages:
  github.com/Wifx/gonetworkmanager/v2:
    interfaces:
      NetworkManager:
      Device:
      DeviceWireless:
      AccessPoint:
      Connection:
      Settings:
      ActiveConnection:
      IP4Config:
  net:
    interfaces:
      Conn:
  github.com/AvengeMedia/danklinux/internal/plugins:
    interfaces:
      GitClient:
  github.com/godbus/dbus/v5:
    interfaces:
      BusObject:
